---     
- hosts: local
  vars_files:
    - external-vars.yaml
  roles:
    - {role: docker, action: "ensure_docker"}
    - {role: docker, action: "clean_containers"}   
    - {role: phoenix, action: "build_custom_images"}
    - {role: wombat, action: "start_wombat_container"}
    - {role: phoenix, action: "start_phoenix_node"}
    - {role: wombat, action: "prepare_wombat", delegate_to: ans-wombat}
    - {role: docker, action: "get_nodes_names", product: "phoenix"}  
    - {role: wombat, action: "add_nodes", delegate_to: ans-wombat}


- hosts: phx_inv
  vars: 
    nodes_names: "{{ hostvars['localhost']['ansible_facts']['nodes_names'] }}"
  roles:
    - {role: check_agents}
    - {role: check_metrics}

- hosts: local
  tasks:
    - name: Generate Phoenix report
      template:
        src: report_template.j2
        dest: reports_html/phoenix.html
      vars:
        inventories: 'phx_inv'

