- name: build custom images if exist
  include: roles/docker/tasks/build_custom_image.yml
  vars:
    custom_docker_image: '{{custom_rmq_docker_image}}{{item}}-management'
    # custom_version: "{{item}}"
    dockerfile: 'Dockerfile.rabbitmq-{{item}}'
    docker_image_args: 
      version: '{{rmq_docker_image}}{{item}}-management'
  with_items: "{{rmq_customized_versions}}"